import { describe, it, expect } from "vitest";
import {
  mkdtempSync,
  readFileSync,
  existsSync,
  statSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { scaffold } from "./scaffold.js";
import { load } from "../config/config.js";
import type { Config } from "../config/config.js";

const makeTempDir = (): string =>
  mkdtempSync(join(tmpdir(), "telesis-scaffold-test-"));

const testConfig = (): Config => ({
  project: {
    name: "TestProject",
    owner: "Test Owner",
    language: "Go",
    status: "active",
    repo: "github.com/test/project",
  },
});

describe("scaffold", () => {
  it("creates config file", () => {
    const rootDir = makeTempDir();
    scaffold(rootDir, testConfig());

    expect(existsSync(join(rootDir, ".telesis", "config.yml"))).toBe(true);

    const loaded = load(rootDir);
    expect(loaded.project.name).toBe("TestProject");
    expect(loaded.project.owner).toBe("Test Owner");
  });

  it("creates document structure", () => {
    const rootDir = makeTempDir();
    scaffold(rootDir, testConfig());

    const expectedFiles = [
      "docs/VISION.md",
      "docs/PRD.md",
      "docs/ARCHITECTURE.md",
      "docs/MILESTONES.md",
    ];
    for (const f of expectedFiles) {
      expect(existsSync(join(rootDir, f))).toBe(true);
    }

    const expectedDirs = ["docs/adr", "docs/tdd", "docs/context"];
    for (const d of expectedDirs) {
      const info = statSync(join(rootDir, d));
      expect(info.isDirectory()).toBe(true);
    }
  });

  it("creates README stubs", () => {
    const rootDir = makeTempDir();
    scaffold(rootDir, testConfig());

    for (const sub of ["adr", "tdd"]) {
      const readmePath = join(rootDir, "docs", sub, "README.md");
      expect(existsSync(readmePath)).toBe(true);
      const content = readFileSync(readmePath, "utf-8");
      expect(content).toContain(sub.toUpperCase());
    }
  });

  it("generates CLAUDE.md", () => {
    const rootDir = makeTempDir();
    scaffold(rootDir, testConfig());

    const claudePath = join(rootDir, "CLAUDE.md");
    expect(existsSync(claudePath)).toBe(true);
    const content = readFileSync(claudePath, "utf-8");
    expect(content).toContain("# TestProject — Claude Context");
    expect(content).toContain("Generated by Telesis on");
  });

  it("doc stubs contain project name", () => {
    const rootDir = makeTempDir();
    scaffold(rootDir, testConfig());

    const docs = ["VISION.md", "PRD.md", "ARCHITECTURE.md", "MILESTONES.md"];
    for (const doc of docs) {
      const content = readFileSync(join(rootDir, "docs", doc), "utf-8");
      expect(content).toContain("TestProject");
    }
  });

  it("fails when already initialized", () => {
    const rootDir = makeTempDir();
    scaffold(rootDir, testConfig());
    expect(() => scaffold(rootDir, testConfig())).toThrow(
      "already initialized",
    );
  });

  it("requires project name", () => {
    const rootDir = makeTempDir();
    const cfg: Config = {
      project: {
        name: "",
        owner: "Test Owner",
        language: "",
        status: "",
        repo: "",
      },
    };
    expect(() => scaffold(rootDir, cfg)).toThrow("project name");
  });

  it("defaults status to active", () => {
    const rootDir = makeTempDir();
    const cfg: Config = {
      project: {
        name: "TestProject",
        owner: "",
        language: "Go",
        status: "",
        repo: "",
      },
    };
    scaffold(rootDir, cfg);

    const loaded = load(rootDir);
    expect(loaded.project.status).toBe("active");
  });

  it("does not mutate caller config", () => {
    const rootDir = makeTempDir();
    const cfg: Config = {
      project: {
        name: "TestProject",
        owner: "",
        language: "Go",
        status: "",
        repo: "",
      },
    };
    scaffold(rootDir, cfg);
    expect(cfg.project.status).toBe("");
  });

  it("doc stubs are non-empty", () => {
    const rootDir = makeTempDir();
    scaffold(rootDir, testConfig());

    const docs = [
      "docs/VISION.md",
      "docs/PRD.md",
      "docs/ARCHITECTURE.md",
      "docs/MILESTONES.md",
    ];
    for (const doc of docs) {
      const data = readFileSync(join(rootDir, doc), "utf-8");
      expect(data.length).toBeGreaterThan(0);
    }
  });

  it("rejects invalid input", () => {
    const tests = [
      {
        name: "rejects newline in project name",
        cfg: {
          project: { name: "Bad\nName", owner: "", language: "", status: "", repo: "" },
        },
        wantErr: "invalid characters",
      },
      {
        name: "rejects null byte in owner",
        cfg: {
          project: {
            name: "Good",
            owner: "Bad\x00Owner",
            language: "",
            status: "",
            repo: "",
          },
        },
        wantErr: "invalid characters",
      },
      {
        name: "rejects template injection in name",
        cfg: {
          project: {
            name: "{{ .Exploit }}",
            owner: "",
            language: "",
            status: "",
            repo: "",
          },
        },
        wantErr: "{{",
      },
      {
        name: "rejects template injection in repo",
        cfg: {
          project: {
            name: "Good",
            owner: "",
            language: "",
            status: "",
            repo: "{{ .Exploit }}",
          },
        },
        wantErr: "{{",
      },
    ];

    for (const tt of tests) {
      const rootDir = makeTempDir();
      expect(() => scaffold(rootDir, tt.cfg)).toThrow(tt.wantErr);
    }
  });
});
