package context_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/delightfulhammers/telesis/internal/config"
	"github.com/delightfulhammers/telesis/internal/context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func setupProject(t *testing.T) string {
	t.Helper()
	rootDir := t.TempDir()

	cfg := &config.Config{
		Project: config.Project{
			Name:     "TestProject",
			Owner:    "Test Owner",
			Language: "Go",
			Status:   "active",
			Repo:     "github.com/test/project",
		},
	}
	require.NoError(t, config.Save(rootDir, cfg))

	// Create docs directory structure
	require.NoError(t, os.MkdirAll(filepath.Join(rootDir, "docs", "adr"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(rootDir, "docs", "tdd"), 0o755))

	return rootDir
}

func TestGenerate(t *testing.T) {
	rootDir := setupProject(t)

	output, err := context.Generate(rootDir)
	require.NoError(t, err)

	assert.Contains(t, output, "# TestProject — Claude Context")
	assert.Contains(t, output, "**Name:** TestProject")
	assert.Contains(t, output, "**Owner:** Test Owner")
	assert.Contains(t, output, "**Primary language:** Go")
	assert.Contains(t, output, "Generated by Telesis on")
}

func TestGenerateIncludesADRCount(t *testing.T) {
	rootDir := setupProject(t)

	// Create some ADR files
	adrDir := filepath.Join(rootDir, "docs", "adr")
	require.NoError(t, os.WriteFile(
		filepath.Join(adrDir, "ADR-001-use-cobra.md"),
		[]byte("# ADR-001: Use Cobra\n\n## Status\nAccepted\n"),
		0o644,
	))
	require.NoError(t, os.WriteFile(
		filepath.Join(adrDir, "ADR-002-use-yaml.md"),
		[]byte("# ADR-002: Use YAML\n\n## Status\nAccepted\n"),
		0o644,
	))

	output, err := context.Generate(rootDir)
	require.NoError(t, err)

	assert.Contains(t, output, "2 decisions on record")
}

func TestGenerateIncludesTDDCount(t *testing.T) {
	rootDir := setupProject(t)

	tddDir := filepath.Join(rootDir, "docs", "tdd")
	require.NoError(t, os.WriteFile(
		filepath.Join(tddDir, "TDD-001-config.md"),
		[]byte("# TDD-001: Config\n"),
		0o644,
	))

	output, err := context.Generate(rootDir)
	require.NoError(t, err)

	assert.Contains(t, output, "1 component designs")
}

func TestGenerateExtractsPrinciples(t *testing.T) {
	rootDir := setupProject(t)

	vision := `# Vision

## Design Principles

1. **First principle.** Details here.
2. **Second principle.** More details.
`
	require.NoError(t, os.WriteFile(
		filepath.Join(rootDir, "docs", "VISION.md"),
		[]byte(vision),
		0o644,
	))

	output, err := context.Generate(rootDir)
	require.NoError(t, err)

	assert.Contains(t, output, "First principle")
	assert.Contains(t, output, "Second principle")
}

func TestGenerateIsIdempotent(t *testing.T) {
	rootDir := setupProject(t)

	output1, err := context.Generate(rootDir)
	require.NoError(t, err)

	output2, err := context.Generate(rootDir)
	require.NoError(t, err)

	// Strip the date line since timestamps differ
	strip := func(s string) string {
		lines := strings.Split(s, "\n")
		var filtered []string
		for _, line := range lines {
			if !strings.Contains(line, "Generated by Telesis on") {
				filtered = append(filtered, line)
			}
		}
		return strings.Join(filtered, "\n")
	}

	assert.Equal(t, strip(output1), strip(output2))
}

func TestGenerateFailsWithoutConfig(t *testing.T) {
	rootDir := t.TempDir()

	_, err := context.Generate(rootDir)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "telesis init")
}

func TestGenerateIncludesADRSummaries(t *testing.T) {
	rootDir := setupProject(t)

	adrDir := filepath.Join(rootDir, "docs", "adr")
	require.NoError(t, os.WriteFile(
		filepath.Join(adrDir, "ADR-001-use-cobra.md"),
		[]byte("# ADR-001: Use Cobra for CLI\n\n## Status\nAccepted\n"),
		0o644,
	))

	output, err := context.Generate(rootDir)
	require.NoError(t, err)

	assert.Contains(t, output, "ADR-001")
	assert.Contains(t, output, "Use Cobra for CLI")
}
