import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { DriftCheck, DriftFinding } from "../types.js";
import { generate } from "../../context/context.js";

const DATE_LINE_RE = /^\*Generated by Telesis on \d{4}-\d{2}-\d{2}\*$/gm;

const normalize = (content: string): string =>
  content.replace(DATE_LINE_RE, "").trim();

export const claudeMdFreshnessCheck: DriftCheck = {
  name: "claude-md-freshness",
  description: "CLAUDE.md matches generated output",
  requiresModel: false,
  run: (rootDir): DriftFinding => {
    const claudePath = join(rootDir, "CLAUDE.md");

    if (!existsSync(claudePath)) {
      return {
        check: "claude-md-freshness",
        passed: false,
        message: "CLAUDE.md not found — run `telesis context` to generate it",
        severity: "warning",
        details: [],
      };
    }

    let expected: string;
    try {
      expected = generate(rootDir);
    } catch (err) {
      return {
        check: "claude-md-freshness",
        passed: false,
        message: `Failed to generate expected CLAUDE.md: ${err instanceof Error ? err.message : String(err)}`,
        severity: "warning",
        details: [],
      };
    }

    const actual = readFileSync(claudePath, "utf-8");

    if (normalize(actual) === normalize(expected)) {
      return {
        check: "claude-md-freshness",
        passed: true,
        message: "CLAUDE.md is up to date",
        severity: "info",
        details: [],
      };
    }

    return {
      check: "claude-md-freshness",
      passed: false,
      message: "CLAUDE.md is out of date — run `telesis context` to regenerate",
      severity: "warning",
      details: [],
    };
  },
};
