import { describe, it, expect } from "vitest";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { save } from "../../config/config.js";
import type { Config } from "../../config/config.js";
import { generate } from "../../context/context.js";
import { useTempDir } from "../../test-utils.js";
import { claudeMdFreshnessCheck } from "./claude-md-freshness.js";

describe("claude-md-freshness", () => {
  const makeTempDir = useTempDir("claude-fresh");

  const setupProject = (): string => {
    const rootDir = makeTempDir();
    const cfg: Config = {
      project: {
        name: "TestProject",
        owner: "Test Owner",
        language: "TypeScript",
        status: "active",
        repo: "github.com/test/project",
      },
    };
    save(rootDir, cfg);
    mkdirSync(join(rootDir, "docs", "adr"), { recursive: true });
    mkdirSync(join(rootDir, "docs", "tdd"), { recursive: true });
    return rootDir;
  };

  it("passes when CLAUDE.md matches generated output", () => {
    const rootDir = setupProject();
    const content = generate(rootDir);
    writeFileSync(join(rootDir, "CLAUDE.md"), content);

    const result = claudeMdFreshnessCheck.run(rootDir);
    expect(result.passed).toBe(true);
    expect(result.message).toContain("up to date");
  });

  it("warns when content differs", () => {
    const rootDir = setupProject();
    writeFileSync(join(rootDir, "CLAUDE.md"), "# Outdated content\n");

    const result = claudeMdFreshnessCheck.run(rootDir);
    expect(result.passed).toBe(false);
    expect(result.message).toContain("telesis context");
  });

  it("passes when only the date line differs", () => {
    const rootDir = setupProject();
    const content = generate(rootDir);
    // Replace date with a different one
    const modified = content.replace(
      /\*Generated by Telesis on \d{4}-\d{2}-\d{2}\*/,
      "*Generated by Telesis on 1999-01-01*",
    );
    writeFileSync(join(rootDir, "CLAUDE.md"), modified);

    const result = claudeMdFreshnessCheck.run(rootDir);
    expect(result.passed).toBe(true);
  });

  it("passes when only the Development Notes section differs", () => {
    const rootDir = setupProject();
    const content = generate(rootDir);
    // Append a notes section that wouldn't exist in CI (notes are gitignored)
    const withNotes =
      content +
      "\n---\n\n## Development Notes\n\n### architecture\n- Agent layer lives under src/agent/ (2026-03-10)\n";
    writeFileSync(join(rootDir, "CLAUDE.md"), withNotes);

    const result = claudeMdFreshnessCheck.run(rootDir);
    expect(result.passed).toBe(true);
  });

  it("warns when CLAUDE.md does not exist", () => {
    const rootDir = setupProject();

    const result = claudeMdFreshnessCheck.run(rootDir);
    expect(result.passed).toBe(false);
    expect(result.message).toContain("not found");
    expect(result.message).toContain("telesis context");
  });

  it("returns warning when generate() throws", () => {
    const rootDir = makeTempDir();
    // No config.yml, so generate() will throw
    writeFileSync(join(rootDir, "CLAUDE.md"), "# Some content\n");

    const result = claudeMdFreshnessCheck.run(rootDir);
    expect(result.passed).toBe(false);
    expect(result.severity).toBe("warning");
    expect(result.message).toContain("Failed to generate");
  });
});
