import { describe, it, expect } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { platform } from "node:process";
import { save } from "../config/config.js";
import type { Config } from "../config/config.js";
import { generate } from "./context.js";

const makeTempDir = (): string =>
  mkdtempSync(join(tmpdir(), "telesis-context-test-"));

const setupProject = (): string => {
  const rootDir = makeTempDir();
  const cfg: Config = {
    project: {
      name: "TestProject",
      owner: "Test Owner",
      language: "Go",
      status: "active",
      repo: "github.com/test/project",
    },
  };
  save(rootDir, cfg);
  mkdirSync(join(rootDir, "docs", "adr"), { recursive: true });
  mkdirSync(join(rootDir, "docs", "tdd"), { recursive: true });
  return rootDir;
};

describe("context.generate", () => {
  it("generates basic CLAUDE.md content", () => {
    const rootDir = setupProject();

    const output = generate(rootDir);

    expect(output).toContain("# TestProject — Claude Context");
    expect(output).toContain("**Name:** TestProject");
    expect(output).toContain("**Owner:** Test Owner");
    expect(output).toContain("**Primary language:** Go");
    expect(output).toContain("Generated by Telesis on");
  });

  it("includes ADR count", () => {
    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");

    writeFileSync(
      join(adrDir, "ADR-001-use-cobra.md"),
      "# ADR-001: Use Cobra\n\n## Status\nAccepted\n",
    );
    writeFileSync(
      join(adrDir, "ADR-002-use-yaml.md"),
      "# ADR-002: Use YAML\n\n## Status\nAccepted\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("2 decisions on record");
  });

  it("includes TDD count", () => {
    const rootDir = setupProject();
    const tddDir = join(rootDir, "docs", "tdd");

    writeFileSync(join(tddDir, "TDD-001-config.md"), "# TDD-001: Config\n");

    const output = generate(rootDir);
    expect(output).toContain("1 component designs");
  });

  it("extracts principles from VISION.md", () => {
    const rootDir = setupProject();

    const vision = `# Vision

## Design Principles

1. **First principle.** Details here.
2. **Second principle.** More details.
`;
    writeFileSync(join(rootDir, "docs", "VISION.md"), vision);

    const output = generate(rootDir);
    expect(output).toContain("First principle");
    expect(output).toContain("Second principle");
  });

  it("is idempotent", () => {
    const rootDir = setupProject();

    const output1 = generate(rootDir);
    const output2 = generate(rootDir);

    const strip = (s: string): string =>
      s
        .split("\n")
        .filter((line) => !line.includes("Generated by Telesis on"))
        .join("\n");

    expect(strip(output1)).toBe(strip(output2));
  });

  it("fails without config", () => {
    const rootDir = makeTempDir();
    expect(() => generate(rootDir)).toThrow("telesis init");
  });

  it("includes ADR summaries", () => {
    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");

    writeFileSync(
      join(adrDir, "ADR-001-use-cobra.md"),
      "# ADR-001: Use Cobra for CLI\n\n## Status\nAccepted\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("ADR-001");
    expect(output).toContain("Use Cobra for CLI");
  });

  it("sorts ADRs numerically and shows last 5", () => {
    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");

    const adrs = [
      { num: "002", title: "Second decision" },
      { num: "010", title: "Tenth decision" },
      { num: "001", title: "First decision" },
      { num: "100", title: "Hundredth decision" },
      { num: "003", title: "Third decision" },
      { num: "020", title: "Twentieth decision" },
    ];

    for (const adr of adrs) {
      const content = `# ADR-${adr.num}: ${adr.title}\n\n## Status\nAccepted\n`;
      writeFileSync(join(adrDir, `ADR-${adr.num}-slug.md`), content);
    }

    const output = generate(rootDir);

    expect(output).toContain("6 decisions on record");
    expect(output).not.toContain("First decision");
    expect(output).toContain("Third decision");
    expect(output).toContain("Tenth decision");
    expect(output).toContain("Twentieth decision");
    expect(output).toContain("Hundredth decision");

    // Verify order
    const idx003 = output.indexOf("Third decision");
    const idx010 = output.indexOf("Tenth decision");
    const idx020 = output.indexOf("Twentieth decision");
    const idx100 = output.indexOf("Hundredth decision");
    expect(idx003).toBeLessThan(idx010);
    expect(idx010).toBeLessThan(idx020);
    expect(idx020).toBeLessThan(idx100);
  });

  it("extracts active (In Progress) milestone", () => {
    const rootDir = setupProject();

    const milestones = `# Milestones

---

## MVP v0.1.0

**Goal:** First milestone.

**Status:** Complete

### Acceptance Criteria

1. Thing one
2. Thing two

---

## v0.2.0 — AI-Powered Init

**Goal:** Second milestone.

**Status:** In Progress

### Acceptance Criteria

1. New thing one
2. New thing two

---

## Future Milestones

More stuff here.
`;
    writeFileSync(join(rootDir, "docs", "MILESTONES.md"), milestones);

    const output = generate(rootDir);
    expect(output).toContain("v0.2.0 — AI-Powered Init");
    expect(output).toContain("Second milestone");
    expect(output).toContain("New thing one");
    expect(output).not.toContain("First milestone");
    expect(output).not.toContain("More stuff here");
  });

  it("falls back to last completed milestone when no active", () => {
    const rootDir = setupProject();

    const milestones = `# Milestones

---

## MVP v0.1.0

**Goal:** Only milestone.

**Status:** Complete

### Acceptance Criteria

1. Done thing

---

## Future Milestones

Upcoming stuff.
`;
    writeFileSync(join(rootDir, "docs", "MILESTONES.md"), milestones);

    const output = generate(rootDir);
    expect(output).toContain("MVP v0.1.0");
    expect(output).toContain("Only milestone");
  });

  it("handles missing optional files gracefully", () => {
    const rootDir = setupProject();
    // No VISION.md or MILESTONES.md

    const output = generate(rootDir);
    expect(output).toContain("# TestProject — Claude Context");
    expect(output).toContain("No ADRs on record yet");
  });

  it("extracts description from VISION.md", () => {
    const rootDir = setupProject();

    const vision = `# Vision

## The Vision

Telesis is a **development intelligence platform** — the control system around autonomous coding agents.

It is the operating layer between the human and the agents.

## What Makes It Different

Other content here.
`;
    writeFileSync(join(rootDir, "docs", "VISION.md"), vision);

    const output = generate(rootDir);
    expect(output).toContain("## About This Project");
    expect(output).toContain("development intelligence platform");
    expect(output).toContain("operating layer");
    expect(output).not.toContain("## The Vision");
    expect(output).not.toContain("Other content here");
  });

  it("description stops at top-level heading", () => {
    const rootDir = setupProject();

    const vision = `# Vision

## The Vision

Description content here.

# Appendix

Appendix content should not appear.
`;
    writeFileSync(join(rootDir, "docs", "VISION.md"), vision);

    const output = generate(rootDir);
    expect(output).toContain("Description content here");
    expect(output).not.toContain("Appendix content should not appear");
  });

  it("includes context files", () => {
    const rootDir = setupProject();

    const contextDir = join(rootDir, "docs", "context");
    mkdirSync(contextDir, { recursive: true });

    writeFileSync(
      join(contextDir, "working-conventions.md"),
      "## Working Conventions\n\nAlways use gofmt.\n",
    );
    writeFileSync(
      join(contextDir, "bop-relationship.md"),
      "## Relationship to Bop\n\nBop is the reviewer agent.\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("Always use gofmt");
    expect(output).toContain("Bop is the reviewer agent");
  });

  it("sorts context files alphabetically", () => {
    const rootDir = setupProject();

    const contextDir = join(rootDir, "docs", "context");
    mkdirSync(contextDir, { recursive: true });

    writeFileSync(
      join(contextDir, "z-last.md"),
      "## Last Section\n\nLast content.\n",
    );
    writeFileSync(
      join(contextDir, "a-first.md"),
      "## First Section\n\nFirst content.\n",
    );

    const output = generate(rootDir);

    const idxFirst = output.indexOf("First content");
    const idxLast = output.indexOf("Last content");
    expect(idxFirst).toBeGreaterThan(-1);
    expect(idxLast).toBeGreaterThan(-1);
    expect(idxFirst).toBeLessThan(idxLast);
  });

  it("handles no context directory", () => {
    const rootDir = setupProject();

    const output = generate(rootDir);
    expect(output).toContain("# TestProject — Claude Context");
  });

  it("ignores non-markdown files in context directory", () => {
    const rootDir = setupProject();

    const contextDir = join(rootDir, "docs", "context");
    mkdirSync(contextDir, { recursive: true });

    writeFileSync(join(contextDir, "notes.txt"), "This should not appear.\n");
    writeFileSync(
      join(contextDir, "valid.md"),
      "## Valid Section\n\nThis should appear.\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("This should appear");
    expect(output).not.toContain("This should not appear");
  });

  it("returns error for unreadable ADR file", () => {
    if (platform === "win32") return; // chmod not reliable on Windows

    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");
    const adrPath = join(adrDir, "ADR-001-broken.md");
    writeFileSync(adrPath, "# ADR-001: Broken\n");
    chmodSync(adrPath, 0o000);

    try {
      expect(() => generate(rootDir)).toThrow("ADR-001");
    } finally {
      chmodSync(adrPath, 0o644);
    }
  });
});
