import { describe, it, expect } from "vitest";
import { mkdirSync, writeFileSync, chmodSync } from "node:fs";
import { join } from "node:path";
import { platform } from "node:process";
import { save } from "../config/config.js";
import type { Config } from "../config/config.js";
import { generate } from "./context.js";
import { appendNote } from "../notes/store.js";
import { useTempDir } from "../test-utils.js";

const makeTempDir = useTempDir("context-test");

const setupProject = (): string => {
  const rootDir = makeTempDir();
  const cfg: Config = {
    project: {
      name: "TestProject",
      owner: "Test Owner",
      language: "Go",
      languages: ["Go"],
      status: "active",
      repo: "github.com/test/project",
    },
  };
  save(rootDir, cfg);
  mkdirSync(join(rootDir, "docs", "adr"), { recursive: true });
  mkdirSync(join(rootDir, "docs", "tdd"), { recursive: true });
  return rootDir;
};

describe("context.generate", () => {
  it("generates basic CLAUDE.md content", () => {
    const rootDir = setupProject();

    const output = generate(rootDir);

    expect(output).toContain("# TestProject — Claude Context");
    expect(output).toContain("**Name:** TestProject");
    expect(output).toContain("**Owner:** Test Owner");
    expect(output).toContain("**Primary language:** Go");
    expect(output).toContain("Generated by Telesis on");
  });

  it("includes ADR count", () => {
    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");

    writeFileSync(
      join(adrDir, "ADR-001-use-cobra.md"),
      "# ADR-001: Use Cobra\n\n## Status\nAccepted\n",
    );
    writeFileSync(
      join(adrDir, "ADR-002-use-yaml.md"),
      "# ADR-002: Use YAML\n\n## Status\nAccepted\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("2 decisions on record");
  });

  it("includes TDD count", () => {
    const rootDir = setupProject();
    const tddDir = join(rootDir, "docs", "tdd");

    writeFileSync(join(tddDir, "TDD-001-config.md"), "# TDD-001: Config\n");

    const output = generate(rootDir);
    expect(output).toContain("1 component designs");
  });

  it("extracts principles from VISION.md", () => {
    const rootDir = setupProject();

    const vision = `# Vision

## Design Principles

1. **First principle.** Details here.
2. **Second principle.** More details.
`;
    writeFileSync(join(rootDir, "docs", "VISION.md"), vision);

    const output = generate(rootDir);
    expect(output).toContain("First principle");
    expect(output).toContain("Second principle");
  });

  it("is idempotent", () => {
    const rootDir = setupProject();

    const output1 = generate(rootDir);
    const output2 = generate(rootDir);

    const strip = (s: string): string =>
      s
        .split("\n")
        .filter((line) => !line.includes("Generated by Telesis on"))
        .join("\n");

    expect(strip(output1)).toBe(strip(output2));
  });

  it("fails without config", () => {
    const rootDir = makeTempDir();
    expect(() => generate(rootDir)).toThrow("telesis init");
  });

  it("includes ADR summaries", () => {
    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");

    writeFileSync(
      join(adrDir, "ADR-001-use-cobra.md"),
      "# ADR-001: Use Cobra for CLI\n\n## Status\nAccepted\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("ADR-001");
    expect(output).toContain("Use Cobra for CLI");
  });

  it("sorts ADRs numerically and shows last 5", () => {
    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");

    const adrs = [
      { num: "002", title: "Second decision" },
      { num: "010", title: "Tenth decision" },
      { num: "001", title: "First decision" },
      { num: "100", title: "Hundredth decision" },
      { num: "003", title: "Third decision" },
      { num: "020", title: "Twentieth decision" },
    ];

    for (const adr of adrs) {
      const content = `# ADR-${adr.num}: ${adr.title}\n\n## Status\nAccepted\n`;
      writeFileSync(join(adrDir, `ADR-${adr.num}-slug.md`), content);
    }

    const output = generate(rootDir);

    expect(output).toContain("6 decisions on record");
    expect(output).not.toContain("First decision");
    expect(output).toContain("Third decision");
    expect(output).toContain("Tenth decision");
    expect(output).toContain("Twentieth decision");
    expect(output).toContain("Hundredth decision");

    // Verify order
    const idx003 = output.indexOf("Third decision");
    const idx010 = output.indexOf("Tenth decision");
    const idx020 = output.indexOf("Twentieth decision");
    const idx100 = output.indexOf("Hundredth decision");
    expect(idx003).toBeLessThan(idx010);
    expect(idx010).toBeLessThan(idx020);
    expect(idx020).toBeLessThan(idx100);
  });

  it("extracts active (In Progress) milestone", () => {
    const rootDir = setupProject();

    const milestones = `# Milestones

---

## MVP v0.1.0

**Goal:** First milestone.

**Status:** Complete

### Acceptance Criteria

1. Thing one
2. Thing two

---

## v0.2.0 — AI-Powered Init

**Goal:** Second milestone.

**Status:** In Progress

### Acceptance Criteria

1. New thing one
2. New thing two

---

## Future Milestones

More stuff here.
`;
    writeFileSync(join(rootDir, "docs", "MILESTONES.md"), milestones);

    const output = generate(rootDir);
    expect(output).toContain("v0.2.0 — AI-Powered Init");
    expect(output).toContain("Second milestone");
    expect(output).toContain("New thing one");
    expect(output).not.toContain("First milestone");
    expect(output).not.toContain("More stuff here");
  });

  it("falls back to last completed milestone when no active", () => {
    const rootDir = setupProject();

    const milestones = `# Milestones

---

## MVP v0.1.0

**Goal:** Only milestone.

**Status:** Complete

### Acceptance Criteria

1. Done thing

---

## Future Milestones

Upcoming stuff.
`;
    writeFileSync(join(rootDir, "docs", "MILESTONES.md"), milestones);

    const output = generate(rootDir);
    expect(output).toContain("MVP v0.1.0");
    expect(output).toContain("Only milestone");
  });

  it("handles missing optional files gracefully", () => {
    const rootDir = setupProject();
    // No VISION.md or MILESTONES.md

    const output = generate(rootDir);
    expect(output).toContain("# TestProject — Claude Context");
    expect(output).toContain("No ADRs on record yet");
  });

  it("extracts description from VISION.md", () => {
    const rootDir = setupProject();

    const vision = `# Vision

## The Vision

Telesis is a **development intelligence platform** — the control system around autonomous coding agents.

It is the operating layer between the human and the agents.

## What Makes It Different

Other content here.
`;
    writeFileSync(join(rootDir, "docs", "VISION.md"), vision);

    const output = generate(rootDir);
    expect(output).toContain("## About This Project");
    expect(output).toContain("development intelligence platform");
    expect(output).toContain("operating layer");
    expect(output).not.toContain("## The Vision");
    expect(output).not.toContain("Other content here");
  });

  it("description stops at top-level heading", () => {
    const rootDir = setupProject();

    const vision = `# Vision

## The Vision

Description content here.

# Appendix

Appendix content should not appear.
`;
    writeFileSync(join(rootDir, "docs", "VISION.md"), vision);

    const output = generate(rootDir);
    expect(output).toContain("Description content here");
    expect(output).not.toContain("Appendix content should not appear");
  });

  it("includes context files", () => {
    const rootDir = setupProject();

    const contextDir = join(rootDir, "docs", "context");
    mkdirSync(contextDir, { recursive: true });

    writeFileSync(
      join(contextDir, "working-conventions.md"),
      "## Working Conventions\n\nAlways use gofmt.\n",
    );
    writeFileSync(
      join(contextDir, "bop-relationship.md"),
      "## Relationship to Bop\n\nBop is the reviewer agent.\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("Always use gofmt");
    expect(output).toContain("Bop is the reviewer agent");
  });

  it("sorts context files alphabetically", () => {
    const rootDir = setupProject();

    const contextDir = join(rootDir, "docs", "context");
    mkdirSync(contextDir, { recursive: true });

    writeFileSync(
      join(contextDir, "z-last.md"),
      "## Last Section\n\nLast content.\n",
    );
    writeFileSync(
      join(contextDir, "a-first.md"),
      "## First Section\n\nFirst content.\n",
    );

    const output = generate(rootDir);

    const idxFirst = output.indexOf("First content");
    const idxLast = output.indexOf("Last content");
    expect(idxFirst).toBeGreaterThan(-1);
    expect(idxLast).toBeGreaterThan(-1);
    expect(idxFirst).toBeLessThan(idxLast);
  });

  it("handles no context directory", () => {
    const rootDir = setupProject();

    const output = generate(rootDir);
    expect(output).toContain("# TestProject — Claude Context");
  });

  it("ignores non-markdown files in context directory", () => {
    const rootDir = setupProject();

    const contextDir = join(rootDir, "docs", "context");
    mkdirSync(contextDir, { recursive: true });

    writeFileSync(join(contextDir, "notes.txt"), "This should not appear.\n");
    writeFileSync(
      join(contextDir, "valid.md"),
      "## Valid Section\n\nThis should appear.\n",
    );

    const output = generate(rootDir);
    expect(output).toContain("This should appear");
    expect(output).not.toContain("This should not appear");
  });

  it("includes Development Notes section when notes exist", () => {
    const rootDir = setupProject();

    appendNote(rootDir, "SSH required for workflow scope", ["git"]);
    appendNote(rootDir, "bop v0.8.4 is the working version", []);

    const output = generate(rootDir);
    expect(output).toContain("## Development Notes");
    expect(output).toContain("### git");
    expect(output).toContain("SSH required for workflow scope");
    expect(output).toContain("### General");
    expect(output).toContain("bop v0.8.4 is the working version");
  });

  it("omits Development Notes section when no notes exist", () => {
    const rootDir = setupProject();

    const output = generate(rootDir);
    expect(output).not.toContain("Development Notes");
  });

  it("returns error for unreadable ADR file", () => {
    if (platform === "win32") return; // chmod not reliable on Windows

    const rootDir = setupProject();
    const adrDir = join(rootDir, "docs", "adr");
    const adrPath = join(adrDir, "ADR-001-broken.md");
    writeFileSync(adrPath, "# ADR-001: Broken\n");
    chmodSync(adrPath, 0o000);

    try {
      expect(() => generate(rootDir)).toThrow("ADR-001");
    } finally {
      chmodSync(adrPath, 0o644);
    }
  });

  describe("layered doc paths", () => {
    const setupWithLayers = (
      layers: Array<{
        path: string;
        include: string[];
      }>,
    ): string => {
      const rootDir = makeTempDir();
      const cfgYaml = [
        "project:",
        "  name: LayerTest",
        "  owner: Test",
        "  languages: [TypeScript]",
        "  status: active",
        "  repo: ''",
        "context:",
        "  layers:",
        ...layers.flatMap((l) => [
          `    - path: "${l.path}"`,
          `      include: [${l.include.join(", ")}]`,
        ]),
      ];
      mkdirSync(join(rootDir, ".telesis"), { recursive: true });
      writeFileSync(
        join(rootDir, ".telesis", "config.yml"),
        cfgYaml.join("\n"),
      );
      return rootDir;
    };

    it("merges ADRs from multiple layers", () => {
      const rootDir = setupWithLayers([
        { path: "shared-docs", include: ["adrs"] },
        { path: "docs", include: ["all"] },
      ]);

      // Create shared-level ADR
      mkdirSync(join(rootDir, "shared-docs", "adr"), { recursive: true });
      writeFileSync(
        join(rootDir, "shared-docs", "adr", "ADR-001-shared.md"),
        "# ADR-001: Shared Decision\n",
      );

      // Create local ADR
      mkdirSync(join(rootDir, "docs", "adr"), { recursive: true });
      writeFileSync(
        join(rootDir, "docs", "adr", "ADR-010-local.md"),
        "# ADR-010: Local Decision\n",
      );
      mkdirSync(join(rootDir, "docs", "tdd"), { recursive: true });

      const output = generate(rootDir);
      expect(output).toContain("ADR-001-shared");
      expect(output).toContain("ADR-010-local");
      expect(output).toContain("2 decisions on record");
    });

    it("respects layer scope — only includes specified doc types", () => {
      const rootDir = setupWithLayers([
        { path: "shared-docs", include: ["adrs"] },
        { path: "docs", include: ["all"] },
      ]);

      // Put a TDD in shared-docs — should NOT be included (scope is adrs only)
      mkdirSync(join(rootDir, "shared-docs", "adr"), { recursive: true });
      mkdirSync(join(rootDir, "shared-docs", "tdd"), { recursive: true });
      writeFileSync(
        join(rootDir, "shared-docs", "tdd", "TDD-001-shared.md"),
        "# TDD-001: Shared\n\n## Overview\nShared TDD\n",
      );
      mkdirSync(join(rootDir, "docs", "adr"), { recursive: true });
      mkdirSync(join(rootDir, "docs", "tdd"), { recursive: true });

      const output = generate(rootDir);
      // Shared TDD should not appear (scope excludes tdds)
      expect(output).not.toContain("TDD-001-shared");
    });

    it("includes context files from multiple layers", () => {
      const rootDir = setupWithLayers([
        { path: "shared-docs", include: ["context"] },
        { path: "docs", include: ["all"] },
      ]);

      mkdirSync(join(rootDir, "shared-docs", "context"), { recursive: true });
      writeFileSync(
        join(rootDir, "shared-docs", "context", "conventions.md"),
        "## Shared Conventions\n\nUse gRPC for all services.\n",
      );

      mkdirSync(join(rootDir, "docs", "adr"), { recursive: true });
      mkdirSync(join(rootDir, "docs", "tdd"), { recursive: true });
      mkdirSync(join(rootDir, "docs", "context"), { recursive: true });
      writeFileSync(
        join(rootDir, "docs", "context", "local.md"),
        "## Local Notes\n\nService-specific stuff.\n",
      );

      const output = generate(rootDir);
      expect(output).toContain("Use gRPC for all services");
      expect(output).toContain("Service-specific stuff");
    });

    it("falls back to default docs/ layer when no config", () => {
      const rootDir = setupProject();
      writeFileSync(
        join(rootDir, "docs", "adr", "ADR-001-test.md"),
        "# ADR-001: Test\n",
      );

      const output = generate(rootDir);
      expect(output).toContain("ADR-001-test");
    });
  });

  describe("TDD inlining", () => {
    it("inlines TDD overview and interfaces in CLAUDE.md", () => {
      const rootDir = setupProject();
      writeFileSync(
        join(rootDir, "docs", "tdd", "TDD-001-auth-layer.md"),
        [
          "# TDD-001 — Auth Layer",
          "",
          "**Status:** Accepted",
          "",
          "## Overview",
          "",
          "The auth layer handles JWT validation and session management.",
          "",
          "## Interfaces",
          "",
          "- `validateToken(token: string): Claims`",
          "- `createSession(userId: string): Session`",
          "",
          "## Data Model",
          "",
          "Sessions stored in Redis.",
        ].join("\n"),
      );

      const output = generate(rootDir);
      expect(output).toContain("Component Designs");
      expect(output).toContain("TDD-001");
      expect(output).toContain("JWT validation and session management");
      expect(output).toContain("validateToken");
      expect(output).toContain("Accepted");
    });

    it("skips superseded TDDs", () => {
      const rootDir = setupProject();
      writeFileSync(
        join(rootDir, "docs", "tdd", "TDD-001-old.md"),
        "# TDD-001 — Old\n\n**Status:** Superseded\n\n## Overview\n\nOld stuff.\n",
      );
      writeFileSync(
        join(rootDir, "docs", "tdd", "TDD-002-current.md"),
        "# TDD-002 — Current\n\n**Status:** Draft\n\n## Overview\n\nCurrent stuff.\n",
      );

      const output = generate(rootDir);
      expect(output).not.toContain("TDD-001");
      expect(output).toContain("TDD-002");
      expect(output).toContain("Current stuff");
    });

    it("limits to 10 most recent TDDs", () => {
      const rootDir = setupProject();
      for (let i = 1; i <= 12; i++) {
        const num = String(i).padStart(3, "0");
        writeFileSync(
          join(rootDir, "docs", "tdd", `TDD-${num}-item.md`),
          `# TDD-${num} — Item ${i}\n\n**Status:** Accepted\n\n## Overview\n\nItem ${i} overview.\n`,
        );
      }

      const output = generate(rootDir);
      // Should include TDD-003 through TDD-012 (10 most recent), not TDD-001 or TDD-002
      expect(output).not.toContain("TDD-001");
      expect(output).not.toContain("TDD-002");
      expect(output).toContain("TDD-003");
      expect(output).toContain("TDD-012");
    });

    it("handles TDDs with no interfaces section", () => {
      const rootDir = setupProject();
      writeFileSync(
        join(rootDir, "docs", "tdd", "TDD-001-simple.md"),
        "# TDD-001 — Simple\n\n**Status:** Draft\n\n## Overview\n\nJust an overview.\n",
      );

      const output = generate(rootDir);
      expect(output).toContain("Just an overview");
      expect(output).toContain("TDD-001");
    });

    it("shows no component designs section when no TDDs exist", () => {
      const rootDir = setupProject();
      const output = generate(rootDir);
      expect(output).not.toContain("Component Designs");
    });
  });
});
