package scaffold_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/delightfulhammers/telesis/internal/config"
	"github.com/delightfulhammers/telesis/internal/scaffold"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func testConfig() *config.Config {
	return &config.Config{
		Project: config.Project{
			Name:     "TestProject",
			Owner:    "Test Owner",
			Language: "Go",
			Status:   "active",
			Repo:     "github.com/test/project",
		},
	}
}

func TestScaffoldCreatesConfigFile(t *testing.T) {
	rootDir := t.TempDir()

	err := scaffold.Scaffold(rootDir, testConfig())
	require.NoError(t, err)

	assert.FileExists(t, filepath.Join(rootDir, ".telesis", "config.yml"))

	loaded, err := config.Load(rootDir)
	require.NoError(t, err)
	assert.Equal(t, "TestProject", loaded.Project.Name)
	assert.Equal(t, "Test Owner", loaded.Project.Owner)
}

func TestScaffoldCreatesDocStructure(t *testing.T) {
	rootDir := t.TempDir()

	err := scaffold.Scaffold(rootDir, testConfig())
	require.NoError(t, err)

	expectedFiles := []string{
		"docs/VISION.md",
		"docs/PRD.md",
		"docs/ARCHITECTURE.md",
		"docs/MILESTONES.md",
	}
	for _, f := range expectedFiles {
		assert.FileExists(t, filepath.Join(rootDir, f), "expected %s to exist", f)
	}

	expectedDirs := []string{
		"docs/adr",
		"docs/tdd",
	}
	for _, d := range expectedDirs {
		info, err := os.Stat(filepath.Join(rootDir, d))
		require.NoError(t, err, "expected %s to exist", d)
		assert.True(t, info.IsDir(), "expected %s to be a directory", d)
	}
}

func TestScaffoldCreatesREADMEStubs(t *testing.T) {
	rootDir := t.TempDir()

	err := scaffold.Scaffold(rootDir, testConfig())
	require.NoError(t, err)

	for _, sub := range []string{"adr", "tdd"} {
		readmePath := filepath.Join(rootDir, "docs", sub, "README.md")
		assert.FileExists(t, readmePath)

		content, err := os.ReadFile(readmePath)
		require.NoError(t, err)
		assert.Contains(t, string(content), strings.ToUpper(sub))
	}
}

func TestScaffoldGeneratesCLAUDEMD(t *testing.T) {
	rootDir := t.TempDir()

	err := scaffold.Scaffold(rootDir, testConfig())
	require.NoError(t, err)

	claudePath := filepath.Join(rootDir, "CLAUDE.md")
	assert.FileExists(t, claudePath)

	content, err := os.ReadFile(claudePath)
	require.NoError(t, err)
	assert.Contains(t, string(content), "# TestProject — Claude Context")
	assert.Contains(t, string(content), "Generated by Telesis on")
}

func TestScaffoldDocStubsContainProjectName(t *testing.T) {
	rootDir := t.TempDir()

	err := scaffold.Scaffold(rootDir, testConfig())
	require.NoError(t, err)

	docs := []string{"VISION.md", "PRD.md", "ARCHITECTURE.md", "MILESTONES.md"}
	for _, doc := range docs {
		content, err := os.ReadFile(filepath.Join(rootDir, "docs", doc))
		require.NoError(t, err, "reading %s", doc)
		assert.Contains(t, string(content), "TestProject", "%s should contain project name", doc)
	}
}

func TestScaffoldFailsWhenAlreadyInitialized(t *testing.T) {
	rootDir := t.TempDir()

	err := scaffold.Scaffold(rootDir, testConfig())
	require.NoError(t, err)

	err = scaffold.Scaffold(rootDir, testConfig())
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "already initialized")
}

func TestScaffoldRequiresProjectName(t *testing.T) {
	rootDir := t.TempDir()

	cfg := &config.Config{
		Project: config.Project{
			Owner: "Test Owner",
		},
	}

	err := scaffold.Scaffold(rootDir, cfg)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "project name")
}

func TestScaffoldDefaultsStatusToActive(t *testing.T) {
	rootDir := t.TempDir()

	cfg := &config.Config{
		Project: config.Project{
			Name:     "TestProject",
			Language: "Go",
		},
	}

	err := scaffold.Scaffold(rootDir, cfg)
	require.NoError(t, err)

	loaded, err := config.Load(rootDir)
	require.NoError(t, err)
	assert.Equal(t, "active", loaded.Project.Status)
}

func TestScaffoldDoesNotMutateCallerConfig(t *testing.T) {
	rootDir := t.TempDir()

	cfg := &config.Config{
		Project: config.Project{
			Name:     "TestProject",
			Language: "Go",
		},
	}

	err := scaffold.Scaffold(rootDir, cfg)
	require.NoError(t, err)

	assert.Equal(t, "", cfg.Project.Status, "caller's config should not be mutated")
}

func TestScaffoldDocStubsAreNonEmpty(t *testing.T) {
	rootDir := t.TempDir()

	err := scaffold.Scaffold(rootDir, testConfig())
	require.NoError(t, err)

	docs := []string{"docs/VISION.md", "docs/PRD.md", "docs/ARCHITECTURE.md", "docs/MILESTONES.md"}
	for _, doc := range docs {
		data, err := os.ReadFile(filepath.Join(rootDir, doc))
		require.NoError(t, err)
		assert.NotEmpty(t, string(data), "%s should not be empty", doc)
	}
}

func TestScaffoldRejectsInvalidInput(t *testing.T) {
	tests := []struct {
		name    string
		cfg     *config.Config
		wantErr string
	}{
		{
			name: "rejects newline in project name",
			cfg: &config.Config{
				Project: config.Project{Name: "Bad\nName"},
			},
			wantErr: "invalid characters",
		},
		{
			name: "rejects null byte in owner",
			cfg: &config.Config{
				Project: config.Project{Name: "Good", Owner: "Bad\x00Owner"},
			},
			wantErr: "invalid characters",
		},
		{
			name: "rejects template injection in name",
			cfg: &config.Config{
				Project: config.Project{Name: "{{ .Exploit }}"},
			},
			wantErr: "{{",
		},
		{
			name: "rejects template injection in repo",
			cfg: &config.Config{
				Project: config.Project{Name: "Good", Repo: "{{ .Exploit }}"},
			},
			wantErr: "{{",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rootDir := t.TempDir()
			err := scaffold.Scaffold(rootDir, tt.cfg)
			assert.Error(t, err)
			assert.Contains(t, err.Error(), tt.wantErr)
		})
	}
}
